"""Añadir tabla SolicitudSubvencion

Revision ID: 32f67c4d1c37
Revises: 24c20016bebc
Create Date: 2025-03-28 09:59:50.922850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f67c4d1c37'
down_revision = '24c20016bebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_subvencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=150), nullable=False),
    sa.Column('concepto', sa.String(length=250), nullable=False),
    sa.Column('tipo_fondo', sa.String(length=100), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('importe_estimado', sa.Float(), nullable=True),
    sa.Column('documentacion_adjunta', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.drop_table('solicitud_subvencion')
    # ### end Alembic commands ###
