"""Añadir campo fecha_presentacion_solicitud a SolicitudSubvencion

Revision ID: 5801502c057d
Revises: d3f764111ecc
Create Date: 2025-04-02 18:37:51.836032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5801502c057d'
down_revision = 'd3f764111ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_subvencion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_presentacion_solicitud', sa.Date(), nullable=True))
        batch_op.drop_column('fecha_solicitud')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_subvencion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_solicitud', sa.DATE(), nullable=True))
        batch_op.drop_column('fecha_presentacion_solicitud')

    # ### end Alembic commands ###
