"""Inicial

Revision ID: 802ade638bd1
Revises: 
Create Date: 2025-03-27 18:52:18.795898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802ade638bd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subvencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_opensea', sa.String(length=50), nullable=True),
    sa.Column('expediente_subvencion', sa.String(length=50), nullable=True),
    sa.Column('entidad', sa.String(length=150), nullable=True),
    sa.Column('concepto', sa.String(length=250), nullable=True),
    sa.Column('tipo_fondo', sa.String(length=100), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('fondos_propios', sa.String(length=10), nullable=True),
    sa.Column('importe_solicitado', sa.Float(), nullable=True),
    sa.Column('importe_concedido', sa.Float(), nullable=True),
    sa.Column('importe_pagado', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subvencion')
    # ### end Alembic commands ###
