"""Arreglo columna rol con valor por defecto

Revision ID: ba101d173824
Revises: 32f67c4d1c37
Create Date: 2025-03-28 10:44:42.592876
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ba101d173824'
down_revision = '32f67c4d1c37'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('rol', sa.String(length=50), nullable=False, server_default='gestor')
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('rol')
    # ### end Alembic commands ###
