"""Añadir modelo Entidad, ContactoEntidad y campos a SolicitudSubvencion

Revision ID: d3f764111ecc
Revises: 85b17ae93b72
Create Date: 2025-04-02 17:42:11.866183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f764111ecc'
down_revision = '85b17ae93b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_historial_solicitud')
    with op.batch_alter_table('contacto_entidad', schema=None) as batch_op:
        batch_op.alter_column('entidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('cargo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('nombre')

    with op.batch_alter_table('entidad', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('historial_solicitud', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)

    with op.batch_alter_table('solicitud_subvencion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expediente_opensea', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('expediente_subvencion', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('entidad_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('importe_subvencionado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fondos_propios', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('documentacion_inicio_expediente', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('documentacion_informe_tecnico', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('documentacion_propuesta_jgl', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('documentacion_ficha_captacion', sa.Boolean(), nullable=True))
        batch_op.alter_column('concepto',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_foreign_key('fk_entidad_id', 'entidad', ['entidad_id'], ['id'])
        batch_op.drop_column('entidad')
        batch_op.drop_column('documentacion_adjunta')

    with op.batch_alter_table('subvencion', schema=None) as batch_op:
        batch_op.alter_column('expediente_opensea',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('expediente_subvencion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('entidad',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('concepto',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('fondos_propios',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('subvencion_denegada', schema=None) as batch_op:
        batch_op.alter_column('entidad',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('concepto',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=200),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('subvencion_denegada', schema=None) as batch_op:
        batch_op.alter_column('concepto',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('entidad',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('subvencion', schema=None) as batch_op:
        batch_op.alter_column('fondos_propios',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('concepto',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('entidad',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('expediente_subvencion',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('expediente_opensea',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('solicitud_subvencion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentacion_adjunta', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('entidad', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint('fk_entidad_id', type_='foreignkey')
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('concepto',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('documentacion_ficha_captacion')
        batch_op.drop_column('documentacion_propuesta_jgl')
        batch_op.drop_column('documentacion_informe_tecnico')
        batch_op.drop_column('documentacion_inicio_expediente')
        batch_op.drop_column('fondos_propios')
        batch_op.drop_column('importe_subvencionado')
        batch_op.drop_column('entidad_id')
        batch_op.drop_column('expediente_subvencion')
        batch_op.drop_column('expediente_opensea')

    with op.batch_alter_table('historial_solicitud', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('entidad', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('contacto_entidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('cargo',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('entidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_historial_solicitud',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('solicitud_id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.Column('usuario', sa.VARCHAR(length=80), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_subvencion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
